language: cpp
compiler: g++
os: windows

dist: xenial

script:
  - git ls-files Snake/ | xargs clang-format -i && git diff --exit-code
  - copy c:\MinGW\bin\mingw32-make.exe c:\MinGW\bin\make.exe
  - make
