os: windows
language: cpp

install:
  - choco install visualstudio2019testagent
  - choco install make

script:
  - git ls-files Snake/ | xargs clang-format -i && git diff --exit-code
  - make
  - make test
  - make runtest
